name: Deploy in beta
on: 
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh 2 commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "Hello world $CLONE_DIR"
            rm -rf /home/john/front-grp1
            git clone -b develop git@github.com:ZohraL/group1-front.git /home/john/front-grp1
            
          